openapi: 3.0.3
info:
  title: Tekton Hub
  description: HTTP services for managing Tekton Hub
  version: "1.0"
servers:
- url: http://api.hub.tekton.dev
paths:
  /v1/query:
    get:
      tags:
      - resource
      summary: Query resource
      description: Find resources by a combination of name, kind and tags
      operationId: resource#Query
      parameters:
      - name: name
        in: query
        description: Name of resource
        allowEmptyValue: true
        schema:
          type: string
          description: Name of resource
          default: ""
          example: buildah
        example: buildah
      - name: kinds
        in: query
        description: Kinds of resource to filter by
        allowEmptyValue: true
        schema:
          type: array
          items:
            type: string
            example: Non sint assumenda non facere ratione eos.
          description: Kinds of resource to filter by
          example:
          - task
          - pipelines
        example:
        - task
        - pipelines
      - name: tags
        in: query
        description: Tags associated with a resource to filter by
        allowEmptyValue: true
        schema:
          type: array
          items:
            type: string
            example: Quis sed dolorem.
          description: Tags associated with a resource to filter by
          example:
          - image
          - build
        example:
        - image
        - build
      - name: limit
        in: query
        description: Maximum number of resources to be returned
        allowEmptyValue: true
        schema:
          type: integer
          description: Maximum number of resources to be returned
          default: 1000
          example: 100
        example: 100
      - name: match
        in: query
        description: Strategy used to find matching resources
        allowEmptyValue: true
        schema:
          type: string
          description: Strategy used to find matching resources
          default: contains
          example: contains
          enum:
          - exact
          - contains
        example: exact
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resources'
              example:
                data:
                - catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
                - catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
                - catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
                - catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /v1/resource/{catalog}/{kind}/{name}:
    get:
      tags:
      - resource
      summary: ByCatalogKindName resource
      description: Find resources using name of catalog, resource name and kind of
        resource
      operationId: resource#ByCatalogKindName
      parameters:
      - name: catalog
        in: path
        description: name of catalog
        required: true
        schema:
          type: string
          description: name of catalog
          example: tektoncd
        example: tektoncd
      - name: kind
        in: path
        description: kind of resource
        required: true
        schema:
          type: string
          description: kind of resource
          example: pipeline
          enum:
          - task
          - pipeline
        example: task
      - name: name
        in: path
        description: Name of resource
        required: true
        schema:
          type: string
          description: Name of resource
          example: buildah
        example: buildah
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
              example:
                data:
                  catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /v1/resource/{catalog}/{kind}/{name}/{version}:
    get:
      tags:
      - resource
      summary: ByCatalogKindNameVersion resource
      description: Find resource using name of catalog & name, kind and version of
        resource
      operationId: resource#ByCatalogKindNameVersion
      parameters:
      - name: catalog
        in: path
        description: name of catalog
        required: true
        schema:
          type: string
          description: name of catalog
          example: tektoncd
        example: tektoncd
      - name: kind
        in: path
        description: kind of resource
        required: true
        schema:
          type: string
          description: kind of resource
          example: pipeline
          enum:
          - task
          - pipeline
        example: task
      - name: name
        in: path
        description: name of resource
        required: true
        schema:
          type: string
          description: name of resource
          example: buildah
        example: buildah
      - name: version
        in: path
        description: version of resource
        required: true
        schema:
          type: string
          description: version of resource
          example: "0.1"
        example: "0.1"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceVersion'
              example:
                data:
                  description: Buildah task builds source into a container image and
                    then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  resource:
                    catalog:
                      id: 1
                      type: community
                    id: 1
                    kind: task
                    name: buildah
                    rating: 4.3
                    tags:
                    - id: 1
                      name: image-build
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /v1/resource/{id}:
    get:
      tags:
      - resource
      summary: ById resource
      description: Find a resource using it's id
      operationId: resource#ById
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        schema:
          type: integer
          description: ID of a resource
          example: 1
        example: 1
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
              example:
                data:
                  catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /v1/resource/{id}/versions:
    get:
      tags:
      - resource
      summary: VersionsByID resource
      description: Find all versions of a resource by its id
      operationId: resource#VersionsByID
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        schema:
          type: integer
          description: ID of a resource
          example: 1
        example: 1
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceVersions'
              example:
                data:
                  latest:
                    id: 2
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
                    version: "0.2"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
                  versions:
                  - id: 1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  - id: 2
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
                    version: "0.2"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /v1/resource/version/{versionID}:
    get:
      tags:
      - resource
      summary: ByVersionId resource
      description: Find a resource using its version's id
      operationId: resource#ByVersionId
      parameters:
      - name: versionID
        in: path
        description: Version ID of a resource's version
        required: true
        schema:
          type: integer
          description: Version ID of a resource's version
          example: 1
        example: 1
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceVersion'
              example:
                data:
                  description: Buildah task builds source into a container image and
                    then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  resource:
                    catalog:
                      id: 1
                      type: community
                    id: 1
                    kind: task
                    name: buildah
                    rating: 4.3
                    tags:
                    - id: 1
                      name: image-build
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /v1/resources:
    get:
      tags:
      - resource
      summary: List resource
      description: List all resources sorted by rating and name
      operationId: resource#List
      parameters:
      - name: limit
        in: query
        description: Maximum number of resources to be returned
        allowEmptyValue: true
        schema:
          type: integer
          description: Maximum number of resources to be returned
          default: 1000
          example: 100
        example: 100
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resources'
              example:
                data:
                - catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
                - catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
                - catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
                - catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  latestVersion:
                    description: Buildah task builds source into a container image
                      and then pushes it to a container registry.
                    displayName: Buildah
                    id: 1
                    minPipelinesVersion: 0.12.1
                    rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                    updatedAt: 2020-01-01 12:00:00 +0000 UTC
                    version: "0.1"
                    webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                  versions:
                  - id: 1
                    version: "0.1"
                  - id: 2
                    version: "0.2"
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /v1/schema/swagger.json:
    get:
      tags:
      - swagger
      summary: Download v1/gen/http/openapi3.yaml
      description: JSON document containing the API swagger definition
      operationId: swagger#/v1/schema/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    Catalog:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of the catalog
          example: 1
        name:
          type: string
          description: Name of catalog
          example: Tekton
        type:
          type: string
          description: Type of catalog
          example: community
          enum:
          - official
          - community
      example:
        id: 1
        name: Tekton
        type: community
      required:
      - id
      - name
      - type
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      description: Internal Server Error
      example:
        fault: true
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: true
        timeout: true
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    Resource:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ResourceData'
      example:
        data:
          catalog:
            id: 1
            type: community
          id: 1
          kind: task
          latestVersion:
            description: Buildah task builds source into a container image and then
              pushes it to a container registry.
            displayName: Buildah
            id: 1
            minPipelinesVersion: 0.12.1
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
            updatedAt: 2020-01-01 12:00:00 +0000 UTC
            version: "0.1"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          name: buildah
          rating: 4.3
          tags:
          - id: 1
            name: image-build
          versions:
          - id: 1
            version: "0.1"
          - id: 2
            version: "0.2"
      required:
      - data
    ResourceData:
      type: object
      properties:
        catalog:
          $ref: '#/components/schemas/Catalog'
        id:
          type: integer
          description: ID is the unique id of the resource
          example: 1
        kind:
          type: string
          description: Kind of resource
          example: task
        latestVersion:
          $ref: '#/components/schemas/ResourceVersionData'
        name:
          type: string
          description: Name of resource
          example: buildah
        rating:
          type: number
          description: Rating of resource
          example: 4.3
          format: double
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Tags related to resource
          example:
          - id: 1
            name: image-build
        versions:
          type: array
          items:
            $ref: '#/components/schemas/ResourceVersionData'
          description: List of all versions of a resource
          example:
          - id: 1
            version: "0.1"
          - id: 2
            version: "0.2"
      description: The resource type describes resource information.
      example:
        catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then
            pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        versions:
        - id: 1
          version: "0.1"
        - id: 2
          version: "0.2"
      required:
      - id
      - name
      - catalog
      - kind
      - latestVersion
      - tags
      - rating
      - versions
    ResourceDataCollection:
      type: array
      items:
        $ref: '#/components/schemas/ResourceData'
      example:
      - catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then
            pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        versions:
        - id: 1
          version: "0.1"
        - id: 2
          version: "0.2"
      - catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then
            pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        versions:
        - id: 1
          version: "0.1"
        - id: 2
          version: "0.2"
      - catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then
            pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        versions:
        - id: 1
          version: "0.1"
        - id: 2
          version: "0.2"
      - catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then
            pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        versions:
        - id: 1
          version: "0.1"
        - id: 2
          version: "0.2"
    ResourceVersion:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ResourceVersionData'
      example:
        data:
          description: Buildah task builds source into a container image and then
            pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          resource:
            catalog:
              id: 1
              type: community
            id: 1
            kind: task
            name: buildah
            rating: 4.3
            tags:
            - id: 1
              name: image-build
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      required:
      - data
    ResourceVersionData:
      type: object
      properties:
        description:
          type: string
          description: Description of version
          example: Buildah task builds source into a container image and then pushes
            it to a container registry.
        displayName:
          type: string
          description: Display name of version
          example: Buildah
        id:
          type: integer
          description: ID is the unique id of resource's version
          example: 1
        minPipelinesVersion:
          type: string
          description: Minimum pipelines version the resource's version is compatible
            with
          example: 0.12.1
        rawURL:
          type: string
          description: Raw URL of resource's yaml file of the version
          example: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          format: uri
        resource:
          $ref: '#/components/schemas/ResourceData'
        updatedAt:
          type: string
          description: Timestamp when version was last updated
          example: 2020-01-01 12:00:00 +0000 UTC
          format: date-time
        version:
          type: string
          description: Version of resource
          example: "0.1"
        webURL:
          type: string
          description: Web URL of resource's yaml file of the version
          example: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          format: uri
      description: The Version result type describes resource's version information.
      example:
        description: Buildah task builds source into a container image and then pushes
          it to a container registry.
        displayName: Buildah
        id: 1
        minPipelinesVersion: 0.12.1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        resource:
          catalog:
            id: 1
            type: community
          id: 1
          kind: task
          name: buildah
          rating: 4.3
          tags:
          - id: 1
            name: image-build
        updatedAt: 2020-01-01 12:00:00 +0000 UTC
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      required:
      - id
      - version
      - displayName
      - description
      - minPipelinesVersion
      - rawURL
      - webURL
      - updatedAt
      - resource
    ResourceVersions:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Versions'
      example:
        data:
          latest:
            id: 2
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
            version: "0.2"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
          versions:
          - id: 1
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
            version: "0.1"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          - id: 2
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
            version: "0.2"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
      required:
      - data
    Resources:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ResourceDataCollection'
      example:
        data:
        - catalog:
            id: 1
            type: community
          id: 1
          kind: task
          latestVersion:
            description: Buildah task builds source into a container image and then
              pushes it to a container registry.
            displayName: Buildah
            id: 1
            minPipelinesVersion: 0.12.1
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
            updatedAt: 2020-01-01 12:00:00 +0000 UTC
            version: "0.1"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          name: buildah
          rating: 4.3
          tags:
          - id: 1
            name: image-build
          versions:
          - id: 1
            version: "0.1"
          - id: 2
            version: "0.2"
        - catalog:
            id: 1
            type: community
          id: 1
          kind: task
          latestVersion:
            description: Buildah task builds source into a container image and then
              pushes it to a container registry.
            displayName: Buildah
            id: 1
            minPipelinesVersion: 0.12.1
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
            updatedAt: 2020-01-01 12:00:00 +0000 UTC
            version: "0.1"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          name: buildah
          rating: 4.3
          tags:
          - id: 1
            name: image-build
          versions:
          - id: 1
            version: "0.1"
          - id: 2
            version: "0.2"
        - catalog:
            id: 1
            type: community
          id: 1
          kind: task
          latestVersion:
            description: Buildah task builds source into a container image and then
              pushes it to a container registry.
            displayName: Buildah
            id: 1
            minPipelinesVersion: 0.12.1
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
            updatedAt: 2020-01-01 12:00:00 +0000 UTC
            version: "0.1"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          name: buildah
          rating: 4.3
          tags:
          - id: 1
            name: image-build
          versions:
          - id: 1
            version: "0.1"
          - id: 2
            version: "0.2"
        - catalog:
            id: 1
            type: community
          id: 1
          kind: task
          latestVersion:
            description: Buildah task builds source into a container image and then
              pushes it to a container registry.
            displayName: Buildah
            id: 1
            minPipelinesVersion: 0.12.1
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
            updatedAt: 2020-01-01 12:00:00 +0000 UTC
            version: "0.1"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          name: buildah
          rating: 4.3
          tags:
          - id: 1
            name: image-build
          versions:
          - id: 1
            version: "0.1"
          - id: 2
            version: "0.2"
      required:
      - data
    Tag:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of tag
          example: 1
        name:
          type: string
          description: Name of tag
          example: image-build
      example:
        id: 1
        name: image-build
      required:
      - id
      - name
    Versions:
      type: object
      properties:
        latest:
          $ref: '#/components/schemas/ResourceVersionData'
        versions:
          type: array
          items:
            $ref: '#/components/schemas/ResourceVersionData'
          description: List of all versions of resource
          example:
          - id: 1
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
            version: "0.1"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          - id: 2
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
            version: "0.2"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
      description: The Versions type describes response for versions by resource id
        API.
      example:
        latest:
          id: 2
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
          version: "0.2"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
        versions:
        - id: 1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        - id: 2
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
          version: "0.2"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
      required:
      - latest
      - versions
