swagger: "2.0"
info:
  title: Tekton Hub
  description: HTTP services for managing Tekton Hub
  version: "0.1"
host: api.hub.tekton.dev
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /categories:
    get:
      tags:
      - category
      summary: list category
      description: List all categories along with their tags sorted by name
      operationId: category#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/CategoryResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/CategoryListInternalErrorResponseBody'
      schemes:
      - http
  /query:
    get:
      tags:
      - resource
      summary: Query resource
      description: Find resources by a combination of name, type
      operationId: resource#Query
      parameters:
      - name: name
        in: query
        description: Name of resource
        required: false
        type: string
        default: ""
      - name: type
        in: query
        description: Type of resource
        required: false
        type: string
        default: ""
        enum:
        - task
        - pipeline
        - ""
      - name: limit
        in: query
        description: Maximum number of resources to be returned
        required: false
        type: integer
        default: 100
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ResourceResourceResponseCollection'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ResourceQueryNotFoundResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ResourceQueryInternalErrorResponseBody'
      schemes:
      - http
  /resource/{id}/versions:
    get:
      tags:
      - resource
      summary: VersionsByID resource
      description: Find all versions of a resource by its id
      operationId: resource#VersionsByID
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ResourceVersionsByIDResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ResourceVersionsByIDNotFoundResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ResourceVersionsByIDInternalErrorResponseBody'
      schemes:
      - http
  /resources:
    get:
      tags:
      - resource
      summary: List resource
      description: List all resources sorted by rating and name
      operationId: resource#List
      parameters:
      - name: limit
        in: query
        description: Maximum number of resources to be returned
        required: false
        type: integer
        default: 100
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ResourceResourceResponseCollection'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ResourceListInternalErrorResponseBody'
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  CatalogResponse:
    title: CatalogResponse
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of the catalog
        example: 1
        format: int64
      type:
        type: string
        description: Type of catalog
        example: community
        enum:
        - official
        - community
    example:
      id: 1
      type: community
    required:
    - id
    - type
  CategoryListInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CategoryResponse:
    title: CategoryResponse
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of the category
        example: 1
        format: int64
      name:
        type: string
        description: Name of category
        example: Image Builder
      tags:
        type: array
        items:
          $ref: '#/definitions/TagResponse'
        description: List of tags associated with the category
        example:
        - id: 1
          name: image-build
        - id: 2
          name: kaniko
    example:
      id: 1
      name: Image Builder
      tags:
      - id: 1
        name: image-build
      - id: 2
        name: kaniko
    required:
    - id
    - name
    - tags
  LatestVersionResponse:
    title: LatestVersionResponse
    type: object
    properties:
      description:
        type: string
        description: Description of version
        example: Buildah task builds source into a container image and then pushes it to a container registry.
      displayName:
        type: string
        description: Display name of version
        example: Buildah
      id:
        type: integer
        description: ID is the unique id of resource's version
        example: 1
        format: int64
      minPipelinesVersion:
        type: string
        description: Minimum pipelines version the resource's version is compatible with
        example: 0.12.1
      rawURL:
        type: string
        description: Raw URL of resource's yaml file of the version
        example: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        format: uri
      updatedAt:
        type: string
        description: Timestamp when version was last updated
        example: 2020-01-01 12:00:00 +0000 UTC
        format: date-time
      version:
        type: string
        description: Version of resource
        example: "0.1"
      webURL:
        type: string
        description: Web URL of resource's yaml file of the version
        example: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        format: uri
    example:
      description: Buildah task builds source into a container image and then pushes it to a container registry.
      displayName: Buildah
      id: 1
      minPipelinesVersion: 0.12.1
      rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
      updatedAt: 2020-01-01 12:00:00 +0000 UTC
      version: "0.1"
      webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
    required:
    - id
    - version
    - description
    - displayName
    - minPipelinesVersion
    - rawURL
    - webURL
    - updatedAt
  ResourceListInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Internal Server Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ResourceQueryInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ResourceQueryNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Resource Not Found Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ResourceResourceResponseCollection:
    title: 'Mediatype identifier: application/vnd.hub.resource; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/ResourceResponse'
    description: QueryResponseBody is the result type for an array of ResourceResponse (default view)
    example:
    - catalog:
        id: 1
        type: community
      id: 1
      latestVersion:
        description: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName: Buildah
        id: 1
        minPipelinesVersion: 0.12.1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        updatedAt: 2020-01-01 12:00:00 +0000 UTC
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      name: buildah
      rating: 4.3
      tags:
      - id: 1
        name: image-build
      type: task
    - catalog:
        id: 1
        type: community
      id: 1
      latestVersion:
        description: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName: Buildah
        id: 1
        minPipelinesVersion: 0.12.1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        updatedAt: 2020-01-01 12:00:00 +0000 UTC
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      name: buildah
      rating: 4.3
      tags:
      - id: 1
        name: image-build
      type: task
  ResourceResponse:
    title: 'Mediatype identifier: application/vnd.hub.resource; view=default'
    type: object
    properties:
      catalog:
        $ref: '#/definitions/CatalogResponse'
      id:
        type: integer
        description: ID is the unique id of the resource
        example: 1
        format: int64
      latestVersion:
        $ref: '#/definitions/LatestVersionResponse'
      name:
        type: string
        description: Name of resource
        example: buildah
      rating:
        type: number
        description: Rating of resource
        example: 4.3
        format: double
      tags:
        type: array
        items:
          $ref: '#/definitions/TagResponse'
        description: Tags related to resource
        example:
        - id: 1
          name: image-build
      type:
        type: string
        description: Type of resource
        example: task
    description: The resource type describes resource information. (default view)
    example:
      catalog:
        id: 1
        type: community
      id: 1
      latestVersion:
        description: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName: Buildah
        id: 1
        minPipelinesVersion: 0.12.1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        updatedAt: 2020-01-01 12:00:00 +0000 UTC
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      name: buildah
      rating: 4.3
      tags:
      - id: 1
        name: image-build
      type: task
    required:
    - id
    - name
    - catalog
    - type
    - latestVersion
    - tags
    - rating
  ResourceVersionsByIDInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ResourceVersionsByIDNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Resource Not Found Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ResourceVersionsByIDResponseBody:
    title: 'Mediatype identifier: application/vnd.hub.versions; view=default'
    type: object
    properties:
      latest:
        $ref: '#/definitions/VersionResponseBody'
      versions:
        type: array
        items:
          $ref: '#/definitions/VersionResponseBody'
        description: List of all versions of resource
        example:
        - id: 1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        - id: 2
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
          version: "0.2"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
    description: VersionsByIDResponseBody result type (default view)
    example:
      latest:
        id: 2
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
        version: "0.2"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
      versions:
      - id: 1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      - id: 2
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
        version: "0.2"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
    required:
    - latest
    - versions
  TagResponse:
    title: TagResponse
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of tag
        example: 1
        format: int64
      name:
        type: string
        description: Name of tag
        example: image-build
    example:
      id: 1
      name: image-build
    required:
    - id
    - name
  VersionResponseBody:
    title: 'Mediatype identifier: application/vnd.hub.version; view=default'
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of resource's version
        example: 1
        format: int64
      rawURL:
        type: string
        description: Raw URL of resource's yaml file of the version
        example: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        format: uri
      version:
        type: string
        description: Version of resource
        example: "0.1"
      webURL:
        type: string
        description: Web URL of resource's yaml file of the version
        example: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        format: uri
    description: The Version result type describes resource's version information.
    example:
      id: 1
      rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
      version: "0.1"
      webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
    required:
    - id
    - version
    - rawURL
    - webURL
