{
	"openapi": "3.0.3",
	"info": {
		"title": "Tekton Hub",
		"description": "HTTP services for managing Tekton Hub",
		"version": "0.1"
	},
	"servers": [{ "url": "http://api.hub.tekton.dev" }],
	"paths": {
		"/": {
			"get": {
				"tags": ["status"],
				"summary": "Status status",
				"description": "Return status 'ok' when the server has started successfully",
				"operationId": "status#Status",
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": { "$ref": "#/components/schemas/StatusResponseBody" },
								"example": { "status": "ok" }
							}
						}
					}
				}
			}
		},
		"/auth/login": {
			"post": {
				"tags": ["auth"],
				"summary": "Authenticate auth",
				"description": "Authenticates users against GitHub OAuth",
				"operationId": "auth#Authenticate",
				"parameters": [
					{
						"name": "code",
						"in": "query",
						"description": "OAuth Authorization code of User",
						"allowEmptyValue": true,
						"required": true,
						"schema": {
							"type": "string",
							"description": "OAuth Authorization code of User",
							"example": "Ex voluptas voluptas."
						},
						"example": "Non molestiae illo aut numquam."
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": { "$ref": "#/components/schemas/AuthenticateResponseBody" },
								"example": { "token": "Minus non." }
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": false
								}
							}
						}
					},
					"401": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": false
								}
							}
						}
					},
					"403": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": false
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": false
								}
							}
						}
					}
				}
			}
		},
		"/categories": {
			"get": {
				"tags": ["category"],
				"summary": "list category",
				"description": "List all categories along with their tags sorted by name",
				"operationId": "category#list",
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": { "$ref": "#/components/schemas/Category" },
									"example": [
										{
											"id": 1,
											"name": "Image Builder",
											"tags": [
												{ "id": 1, "name": "image-build" },
												{ "id": 2, "name": "kaniko" }
											]
										},
										{
											"id": 1,
											"name": "Image Builder",
											"tags": [
												{ "id": 1, "name": "image-build" },
												{ "id": 2, "name": "kaniko" }
											]
										}
									]
								},
								"example": [
									{
										"id": 1,
										"name": "Image Builder",
										"tags": [
											{ "id": 1, "name": "image-build" },
											{ "id": 2, "name": "kaniko" }
										]
									},
									{
										"id": 1,
										"name": "Image Builder",
										"tags": [
											{ "id": 1, "name": "image-build" },
											{ "id": 2, "name": "kaniko" }
										]
									},
									{
										"id": 1,
										"name": "Image Builder",
										"tags": [
											{ "id": 1, "name": "image-build" },
											{ "id": 2, "name": "kaniko" }
										]
									}
								]
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": true
								}
							}
						}
					}
				}
			}
		},
		"/query": {
			"get": {
				"tags": ["resource"],
				"summary": "Query resource",
				"description": "Find resources by a combination of name, kind",
				"operationId": "resource#Query",
				"parameters": [
					{
						"name": "name",
						"in": "query",
						"description": "Name of resource",
						"allowEmptyValue": true,
						"schema": {
							"type": "string",
							"description": "Name of resource",
							"default": "",
							"example": "Sunt voluptas."
						},
						"example": "Non illo accusantium aut iste."
					},
					{
						"name": "kind",
						"in": "query",
						"description": "Kind of resource",
						"allowEmptyValue": true,
						"schema": {
							"type": "string",
							"description": "Kind of resource",
							"default": "",
							"example": "",
							"enum": ["task", "pipeline", ""]
						},
						"example": "task"
					},
					{
						"name": "limit",
						"in": "query",
						"description": "Maximum number of resources to be returned",
						"allowEmptyValue": true,
						"schema": {
							"type": "integer",
							"description": "Maximum number of resources to be returned",
							"default": 100,
							"example": 11050074737756324455
						},
						"example": 586563961979287619
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ResourceResponseWithoutVersionCollection"
								},
								"example": [
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									},
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									},
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									}
								]
							}
						}
					},
					"404": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": true
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": true
								}
							}
						}
					}
				}
			}
		},
		"/resource/version/{versionID}": {
			"get": {
				"tags": ["resource"],
				"summary": "ByVersionId resource",
				"description": "Find a resource using its version's id",
				"operationId": "resource#ByVersionId",
				"parameters": [
					{
						"name": "versionID",
						"in": "path",
						"description": "Version ID of a resource's version",
						"required": true,
						"schema": {
							"type": "integer",
							"description": "Version ID of a resource's version",
							"example": 7020124732932627545
						},
						"example": 8774254641291276041
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": { "$ref": "#/components/schemas/ByKindNameVersionResponseBody" },
								"example": {
									"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
									"displayName": "Buildah",
									"id": 1,
									"minPipelinesVersion": "0.12.1",
									"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
									"resource": {
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									},
									"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
									"version": "0.1",
									"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
								}
							}
						}
					},
					"404": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": false
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": true
								}
							}
						}
					}
				}
			}
		},
		"/resource/{id}": {
			"get": {
				"tags": ["resource"],
				"summary": "ById resource",
				"description": "Find a resource using it's id",
				"operationId": "resource#ById",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of a resource",
						"required": true,
						"schema": {
							"type": "integer",
							"description": "ID of a resource",
							"example": 8532871935680991006
						},
						"example": 13634412409473818701
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": { "$ref": "#/components/schemas/ByIDResponseBody" },
								"example": {
									"catalog": { "id": 1, "type": "community" },
									"id": 1,
									"kind": "task",
									"latestVersion": {
										"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
										"displayName": "Buildah",
										"id": 1,
										"minPipelinesVersion": "0.12.1",
										"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
										"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
										"version": "0.1",
										"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
									},
									"name": "buildah",
									"rating": 4.3,
									"tags": [{ "id": 1, "name": "image-build" }],
									"versions": [
										{ "id": 1, "version": "0.1" },
										{ "id": 2, "version": "0.2" }
									]
								}
							}
						}
					},
					"404": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": true
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": false
								}
							}
						}
					}
				}
			}
		},
		"/resource/{id}/rating": {
			"get": {
				"tags": ["rating"],
				"summary": "Get rating",
				"description": "Find user's rating for a resource",
				"operationId": "rating#Get",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of a resource",
						"required": true,
						"schema": {
							"type": "integer",
							"description": "ID of a resource",
							"example": 18155772433203039283
						},
						"example": 1662274528396721817
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": { "$ref": "#/components/schemas/GetResponseBody" },
								"example": { "rating": 5810980781280769611 }
							}
						}
					},
					"401": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": true
								}
							}
						}
					},
					"403": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": false
								}
							}
						}
					},
					"404": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": false
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": false
								}
							}
						}
					}
				},
				"security": [{ "jwt_header_Authorization": ["rating:read", "rating:write"] }]
			}
		},
		"/resource/{id}/versions": {
			"get": {
				"tags": ["resource"],
				"summary": "VersionsByID resource",
				"description": "Find all versions of a resource by its id",
				"operationId": "resource#VersionsByID",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of a resource",
						"required": true,
						"schema": {
							"type": "integer",
							"description": "ID of a resource",
							"example": 10758898425274697515
						},
						"example": 4202948814925793120
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": { "$ref": "#/components/schemas/Versions" },
								"example": {
									"latest": {
										"id": 2,
										"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml",
										"version": "0.2",
										"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml"
									},
									"versions": [
										{
											"id": 1,
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										{
											"id": 2,
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml",
											"version": "0.2",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml"
										}
									]
								}
							}
						}
					},
					"404": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": false
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": true
								}
							}
						}
					}
				}
			}
		},
		"/resource/{kind}/{name}": {
			"get": {
				"tags": ["resource"],
				"summary": "ByKindName resource",
				"description": "Find resources using name and kind",
				"operationId": "resource#ByKindName",
				"parameters": [
					{
						"name": "kind",
						"in": "path",
						"description": "kind of resource",
						"required": true,
						"schema": {
							"type": "string",
							"description": "kind of resource",
							"example": "task",
							"enum": ["task", "pipeline"]
						},
						"example": "task"
					},
					{
						"name": "name",
						"in": "path",
						"description": "Name of resource",
						"required": true,
						"schema": {
							"type": "string",
							"description": "Name of resource",
							"example": "Ut ut debitis quia sed."
						},
						"example": "Velit dolorem voluptatem."
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ResourceResponseWithoutVersionCollection"
								},
								"example": [
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									},
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									},
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									}
								]
							}
						}
					},
					"404": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": false
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": true
								}
							}
						}
					}
				}
			}
		},
		"/resource/{kind}/{name}/{version}": {
			"get": {
				"tags": ["resource"],
				"summary": "ByKindNameVersion resource",
				"description": "Find resource using name, kind and version of resource",
				"operationId": "resource#ByKindNameVersion",
				"parameters": [
					{
						"name": "kind",
						"in": "path",
						"description": "kind of resource",
						"required": true,
						"schema": {
							"type": "string",
							"description": "kind of resource",
							"example": "task",
							"enum": ["task", "pipeline"]
						},
						"example": "pipeline"
					},
					{
						"name": "name",
						"in": "path",
						"description": "name of resource",
						"required": true,
						"schema": {
							"type": "string",
							"description": "name of resource",
							"example": "Consequuntur autem enim tenetur."
						},
						"example": "Inventore quis consequatur mollitia aut neque similique."
					},
					{
						"name": "version",
						"in": "path",
						"description": "version of resource",
						"required": true,
						"schema": {
							"type": "string",
							"description": "version of resource",
							"example": "Ad dicta."
						},
						"example": "Fugiat sequi eum in similique labore."
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": { "$ref": "#/components/schemas/ByKindNameVersionResponseBody" },
								"example": {
									"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
									"displayName": "Buildah",
									"id": 1,
									"minPipelinesVersion": "0.12.1",
									"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
									"resource": {
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									},
									"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
									"version": "0.1",
									"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
								}
							}
						}
					},
					"404": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": true
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": false,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": true,
									"timeout": false
								}
							}
						}
					}
				}
			}
		},
		"/resources": {
			"get": {
				"tags": ["resource"],
				"summary": "List resource",
				"description": "List all resources sorted by rating and name",
				"operationId": "resource#List",
				"parameters": [
					{
						"name": "limit",
						"in": "query",
						"description": "Maximum number of resources to be returned",
						"allowEmptyValue": true,
						"schema": {
							"type": "integer",
							"description": "Maximum number of resources to be returned",
							"default": 100,
							"example": 15733382438968306493
						},
						"example": 8994252780272272546
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ResourceResponseWithoutVersionCollection"
								},
								"example": [
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									},
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									},
									{
										"catalog": { "id": 1, "type": "community" },
										"id": 1,
										"kind": "task",
										"latestVersion": {
											"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
											"displayName": "Buildah",
											"id": 1,
											"minPipelinesVersion": "0.12.1",
											"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
											"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
											"version": "0.1",
											"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
										},
										"name": "buildah",
										"rating": 4.3,
										"tags": [{ "id": 1, "name": "image-build" }]
									}
								]
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/vnd.goa.error": {
								"schema": { "$ref": "#/components/schemas/Error" },
								"example": {
									"fault": true,
									"id": "123abc",
									"message": "parameter 'p' must be an integer",
									"name": "bad_request",
									"temporary": false,
									"timeout": false
								}
							}
						}
					}
				}
			}
		},
		"/swagger/swagger.json": {
			"get": {
				"tags": ["swagger"],
				"summary": "Download gen/http/openapi.json",
				"description": "JSON document containing the API swagger definition",
				"operationId": "swagger#/swagger/swagger.json",
				"responses": { "200": { "description": "File downloaded" } }
			}
		}
	},
	"components": {
		"schemas": {
			"AuthenticateResponseBody": {
				"type": "object",
				"properties": {
					"token": {
						"type": "string",
						"description": "JWT",
						"example": "Dolores dolor esse officia velit aliquid praesentium."
					}
				},
				"example": { "token": "Sed optio ab beatae est." },
				"required": ["token"]
			},
			"ByIDResponseBody": {
				"type": "object",
				"properties": {
					"catalog": { "$ref": "#/components/schemas/Catalog" },
					"id": {
						"type": "integer",
						"description": "ID is the unique id of the resource",
						"example": 1
					},
					"kind": { "type": "string", "description": "Kind of resource", "example": "task" },
					"latestVersion": { "$ref": "#/components/schemas/Version" },
					"name": { "type": "string", "description": "Name of resource", "example": "buildah" },
					"rating": {
						"type": "number",
						"description": "Rating of resource",
						"example": 4.3,
						"format": "double"
					},
					"tags": {
						"type": "array",
						"items": { "$ref": "#/components/schemas/Tag" },
						"description": "Tags related to resource",
						"example": [{ "id": 1, "name": "image-build" }]
					},
					"versions": {
						"type": "array",
						"items": { "$ref": "#/components/schemas/Version3" },
						"description": "List of all versions of a resource",
						"example": [
							{ "id": 1, "version": "0.1" },
							{ "id": 2, "version": "0.2" }
						]
					}
				},
				"description": "ByIdResponseBody result type (default view)",
				"example": {
					"catalog": { "id": 1, "type": "community" },
					"id": 1,
					"kind": "task",
					"latestVersion": {
						"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
						"displayName": "Buildah",
						"id": 1,
						"minPipelinesVersion": "0.12.1",
						"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
						"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
						"version": "0.1",
						"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
					},
					"name": "buildah",
					"rating": 4.3,
					"tags": [{ "id": 1, "name": "image-build" }],
					"versions": [
						{ "id": 1, "version": "0.1" },
						{ "id": 2, "version": "0.2" }
					]
				},
				"required": ["id", "name", "catalog", "kind", "latestVersion", "tags", "rating", "versions"]
			},
			"ByKindNameVersionResponseBody": {
				"type": "object",
				"properties": {
					"description": {
						"type": "string",
						"description": "Description of version",
						"example": "Buildah task builds source into a container image and then pushes it to a container registry."
					},
					"displayName": {
						"type": "string",
						"description": "Display name of version",
						"example": "Buildah"
					},
					"id": {
						"type": "integer",
						"description": "ID is the unique id of resource's version",
						"example": 1
					},
					"minPipelinesVersion": {
						"type": "string",
						"description": "Minimum pipelines version the resource's version is compatible with",
						"example": "0.12.1"
					},
					"rawURL": {
						"type": "string",
						"description": "Raw URL of resource's yaml file of the version",
						"example": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
						"format": "uri"
					},
					"resource": { "$ref": "#/components/schemas/Resource2" },
					"updatedAt": {
						"type": "string",
						"description": "Timestamp when version was last updated",
						"example": "2020-01-01 12:00:00 +0000 UTC",
						"format": "date-time"
					},
					"version": { "type": "string", "description": "Version of resource", "example": "0.1" },
					"webURL": {
						"type": "string",
						"description": "Web URL of resource's yaml file of the version",
						"example": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml",
						"format": "uri"
					}
				},
				"description": "ByKindNameVersionResponseBody result type (default view)",
				"example": {
					"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
					"displayName": "Buildah",
					"id": 1,
					"minPipelinesVersion": "0.12.1",
					"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
					"resource": {
						"catalog": { "id": 1, "type": "community" },
						"id": 1,
						"kind": "task",
						"name": "buildah",
						"rating": 4.3,
						"tags": [{ "id": 1, "name": "image-build" }]
					},
					"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
					"version": "0.1",
					"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
				},
				"required": [
					"id",
					"version",
					"displayName",
					"description",
					"minPipelinesVersion",
					"rawURL",
					"webURL",
					"updatedAt",
					"resource"
				]
			},
			"Catalog": {
				"type": "object",
				"properties": {
					"id": {
						"type": "integer",
						"description": "ID is the unique id of the catalog",
						"example": 1
					},
					"type": {
						"type": "string",
						"description": "Type of catalog",
						"example": "community",
						"enum": ["official", "community"]
					}
				},
				"example": { "id": 1, "type": "community" },
				"required": ["id", "type"]
			},
			"Category": {
				"type": "object",
				"properties": {
					"id": {
						"type": "integer",
						"description": "ID is the unique id of the category",
						"example": 1
					},
					"name": {
						"type": "string",
						"description": "Name of category",
						"example": "Image Builder"
					},
					"tags": {
						"type": "array",
						"items": { "$ref": "#/components/schemas/Tag" },
						"description": "List of tags associated with the category",
						"example": [
							{ "id": 1, "name": "image-build" },
							{ "id": 2, "name": "kaniko" }
						]
					}
				},
				"example": {
					"id": 1,
					"name": "Image Builder",
					"tags": [
						{ "id": 1, "name": "image-build" },
						{ "id": 2, "name": "kaniko" }
					]
				},
				"required": ["id", "name", "tags"]
			},
			"Error": {
				"type": "object",
				"properties": {
					"fault": {
						"type": "boolean",
						"description": "Is the error a server-side fault?",
						"example": false
					},
					"id": {
						"type": "string",
						"description": "ID is a unique identifier for this particular occurrence of the problem.",
						"example": "123abc"
					},
					"message": {
						"type": "string",
						"description": "Message is a human-readable explanation specific to this occurrence of the problem.",
						"example": "parameter 'p' must be an integer"
					},
					"name": {
						"type": "string",
						"description": "Name is the name of this class of errors.",
						"example": "bad_request"
					},
					"temporary": {
						"type": "boolean",
						"description": "Is the error temporary?",
						"example": true
					},
					"timeout": {
						"type": "boolean",
						"description": "Is the error a timeout?",
						"example": false
					}
				},
				"description": "Internal Server Error",
				"example": {
					"fault": true,
					"id": "123abc",
					"message": "parameter 'p' must be an integer",
					"name": "bad_request",
					"temporary": false,
					"timeout": true
				},
				"required": ["name", "id", "message", "temporary", "timeout", "fault"]
			},
			"GetResponseBody": {
				"type": "object",
				"properties": {
					"rating": {
						"type": "integer",
						"description": "User rating for resource",
						"example": 9034773561342663560,
						"format": "int64"
					}
				},
				"example": { "rating": 2173913504320892407 },
				"required": ["rating"]
			},
			"Resource": {
				"type": "object",
				"properties": {
					"catalog": { "$ref": "#/components/schemas/Catalog" },
					"id": {
						"type": "integer",
						"description": "ID is the unique id of the resource",
						"example": 1
					},
					"kind": { "type": "string", "description": "Kind of resource", "example": "task" },
					"latestVersion": { "$ref": "#/components/schemas/Version2" },
					"name": { "type": "string", "description": "Name of resource", "example": "buildah" },
					"rating": {
						"type": "number",
						"description": "Rating of resource",
						"example": 4.3,
						"format": "double"
					},
					"tags": {
						"type": "array",
						"items": { "$ref": "#/components/schemas/Tag" },
						"description": "Tags related to resource",
						"example": [{ "id": 1, "name": "image-build" }]
					},
					"versions": {
						"type": "array",
						"items": { "$ref": "#/components/schemas/Version2" },
						"description": "List of all versions of a resource",
						"example": [
							{ "id": 1, "version": "0.1" },
							{ "id": 2, "version": "0.2" }
						]
					}
				},
				"description": "The resource type describes resource information.",
				"example": {
					"catalog": { "id": 1, "type": "community" },
					"id": 1,
					"kind": "task",
					"latestVersion": {
						"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
						"displayName": "Buildah",
						"id": 1,
						"minPipelinesVersion": "0.12.1",
						"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
						"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
						"version": "0.1",
						"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
					},
					"name": "buildah",
					"rating": 4.3,
					"tags": [{ "id": 1, "name": "image-build" }],
					"versions": [
						{ "id": 1, "version": "0.1" },
						{ "id": 2, "version": "0.2" }
					]
				},
				"required": ["id", "name", "catalog", "kind", "latestVersion", "tags", "rating", "versions"]
			},
			"Resource2": {
				"type": "object",
				"properties": {
					"catalog": { "$ref": "#/components/schemas/Catalog" },
					"id": {
						"type": "integer",
						"description": "ID is the unique id of the resource",
						"example": 1
					},
					"kind": { "type": "string", "description": "Kind of resource", "example": "task" },
					"name": { "type": "string", "description": "Name of resource", "example": "buildah" },
					"rating": {
						"type": "number",
						"description": "Rating of resource",
						"example": 4.3,
						"format": "double"
					},
					"tags": {
						"type": "array",
						"items": { "$ref": "#/components/schemas/Tag" },
						"description": "Tags related to resource",
						"example": [{ "id": 1, "name": "image-build" }]
					}
				},
				"description": "The resource type describes resource information.",
				"example": {
					"catalog": { "id": 1, "type": "community" },
					"id": 1,
					"kind": "task",
					"name": "buildah",
					"rating": 4.3,
					"tags": [{ "id": 1, "name": "image-build" }]
				},
				"required": ["id", "name", "catalog", "kind", "latestVersion", "tags", "rating", "versions"]
			},
			"ResourceResponseWithoutVersion": {
				"type": "object",
				"properties": {
					"catalog": { "$ref": "#/components/schemas/Catalog" },
					"id": {
						"type": "integer",
						"description": "ID is the unique id of the resource",
						"example": 1
					},
					"kind": { "type": "string", "description": "Kind of resource", "example": "task" },
					"latestVersion": { "$ref": "#/components/schemas/Version" },
					"name": { "type": "string", "description": "Name of resource", "example": "buildah" },
					"rating": {
						"type": "number",
						"description": "Rating of resource",
						"example": 4.3,
						"format": "double"
					},
					"tags": {
						"type": "array",
						"items": { "$ref": "#/components/schemas/Tag" },
						"description": "Tags related to resource",
						"example": [{ "id": 1, "name": "image-build" }]
					}
				},
				"description": "The resource type describes resource information. (withoutVersion view)",
				"example": {
					"catalog": { "id": 1, "type": "community" },
					"id": 1,
					"kind": "task",
					"latestVersion": {
						"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
						"displayName": "Buildah",
						"id": 1,
						"minPipelinesVersion": "0.12.1",
						"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
						"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
						"version": "0.1",
						"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
					},
					"name": "buildah",
					"rating": 4.3,
					"tags": [{ "id": 1, "name": "image-build" }]
				},
				"required": ["id", "name", "catalog", "kind", "latestVersion", "tags", "rating"]
			},
			"ResourceResponseWithoutVersionCollection": {
				"type": "array",
				"items": { "$ref": "#/components/schemas/ResourceResponseWithoutVersion" },
				"description": "QueryResponseBody is the result type for an array of ResourceResponse (withoutVersion view)",
				"example": [
					{
						"catalog": { "id": 1, "type": "community" },
						"id": 1,
						"kind": "task",
						"latestVersion": {
							"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
							"displayName": "Buildah",
							"id": 1,
							"minPipelinesVersion": "0.12.1",
							"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
							"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
							"version": "0.1",
							"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
						},
						"name": "buildah",
						"rating": 4.3,
						"tags": [{ "id": 1, "name": "image-build" }]
					},
					{
						"catalog": { "id": 1, "type": "community" },
						"id": 1,
						"kind": "task",
						"latestVersion": {
							"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
							"displayName": "Buildah",
							"id": 1,
							"minPipelinesVersion": "0.12.1",
							"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
							"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
							"version": "0.1",
							"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
						},
						"name": "buildah",
						"rating": 4.3,
						"tags": [{ "id": 1, "name": "image-build" }]
					},
					{
						"catalog": { "id": 1, "type": "community" },
						"id": 1,
						"kind": "task",
						"latestVersion": {
							"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
							"displayName": "Buildah",
							"id": 1,
							"minPipelinesVersion": "0.12.1",
							"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
							"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
							"version": "0.1",
							"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
						},
						"name": "buildah",
						"rating": 4.3,
						"tags": [{ "id": 1, "name": "image-build" }]
					}
				]
			},
			"StatusResponseBody": {
				"type": "object",
				"properties": {
					"status": { "type": "string", "description": "Status of server", "example": "ok" }
				},
				"example": { "status": "ok" },
				"required": ["status"]
			},
			"Tag": {
				"type": "object",
				"properties": {
					"id": { "type": "integer", "description": "ID is the unique id of tag", "example": 1 },
					"name": { "type": "string", "description": "Name of tag", "example": "image-build" }
				},
				"example": { "id": 1, "name": "image-build" },
				"required": ["id", "name"]
			},
			"Version": {
				"type": "object",
				"properties": {
					"description": {
						"type": "string",
						"description": "Description of version",
						"example": "Buildah task builds source into a container image and then pushes it to a container registry."
					},
					"displayName": {
						"type": "string",
						"description": "Display name of version",
						"example": "Buildah"
					},
					"id": {
						"type": "integer",
						"description": "ID is the unique id of resource's version",
						"example": 1
					},
					"minPipelinesVersion": {
						"type": "string",
						"description": "Minimum pipelines version the resource's version is compatible with",
						"example": "0.12.1"
					},
					"rawURL": {
						"type": "string",
						"description": "Raw URL of resource's yaml file of the version",
						"example": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
						"format": "uri"
					},
					"updatedAt": {
						"type": "string",
						"description": "Timestamp when version was last updated",
						"example": "2020-01-01 12:00:00 +0000 UTC",
						"format": "date-time"
					},
					"version": { "type": "string", "description": "Version of resource", "example": "0.1" },
					"webURL": {
						"type": "string",
						"description": "Web URL of resource's yaml file of the version",
						"example": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml",
						"format": "uri"
					}
				},
				"description": "The Version result type describes resource's version information.",
				"example": {
					"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
					"displayName": "Buildah",
					"id": 1,
					"minPipelinesVersion": "0.12.1",
					"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
					"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
					"version": "0.1",
					"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
				},
				"required": [
					"id",
					"version",
					"displayName",
					"description",
					"minPipelinesVersion",
					"rawURL",
					"webURL",
					"updatedAt",
					"resource"
				]
			},
			"Version2": {
				"type": "object",
				"properties": {
					"description": {
						"type": "string",
						"description": "Description of version",
						"example": "Buildah task builds source into a container image and then pushes it to a container registry."
					},
					"displayName": {
						"type": "string",
						"description": "Display name of version",
						"example": "Buildah"
					},
					"id": {
						"type": "integer",
						"description": "ID is the unique id of resource's version",
						"example": 1
					},
					"minPipelinesVersion": {
						"type": "string",
						"description": "Minimum pipelines version the resource's version is compatible with",
						"example": "0.12.1"
					},
					"rawURL": {
						"type": "string",
						"description": "Raw URL of resource's yaml file of the version",
						"example": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
						"format": "uri"
					},
					"resource": { "$ref": "#/components/schemas/Resource" },
					"updatedAt": {
						"type": "string",
						"description": "Timestamp when version was last updated",
						"example": "2020-01-01 12:00:00 +0000 UTC",
						"format": "date-time"
					},
					"version": { "type": "string", "description": "Version of resource", "example": "0.1" },
					"webURL": {
						"type": "string",
						"description": "Web URL of resource's yaml file of the version",
						"example": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml",
						"format": "uri"
					}
				},
				"description": "The Version result type describes resource's version information.",
				"example": {
					"description": "Buildah task builds source into a container image and then pushes it to a container registry.",
					"displayName": "Buildah",
					"id": 1,
					"minPipelinesVersion": "0.12.1",
					"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
					"resource": {
						"catalog": { "id": 1, "type": "community" },
						"id": 1,
						"kind": "task",
						"name": "buildah",
						"rating": 4.3,
						"tags": [{ "id": 1, "name": "image-build" }]
					},
					"updatedAt": "2020-01-01 12:00:00 +0000 UTC",
					"version": "0.1",
					"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
				},
				"required": [
					"id",
					"version",
					"displayName",
					"description",
					"minPipelinesVersion",
					"rawURL",
					"webURL",
					"updatedAt",
					"resource"
				]
			},
			"Version3": {
				"type": "object",
				"properties": {
					"id": {
						"type": "integer",
						"description": "ID is the unique id of resource's version",
						"example": 1
					},
					"version": { "type": "string", "description": "Version of resource", "example": "0.1" }
				},
				"description": "The Version result type describes resource's version information.",
				"example": { "id": 1, "version": "0.1" },
				"required": [
					"id",
					"version",
					"displayName",
					"description",
					"minPipelinesVersion",
					"rawURL",
					"webURL",
					"updatedAt",
					"resource"
				]
			},
			"Versions": {
				"type": "object",
				"properties": {
					"latest": { "$ref": "#/components/schemas/Version2" },
					"versions": {
						"type": "array",
						"items": { "$ref": "#/components/schemas/Version2" },
						"description": "List of all versions of resource",
						"example": [
							{
								"id": 1,
								"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
								"version": "0.1",
								"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
							},
							{
								"id": 2,
								"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml",
								"version": "0.2",
								"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml"
							}
						]
					}
				},
				"example": {
					"latest": {
						"id": 2,
						"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml",
						"version": "0.2",
						"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml"
					},
					"versions": [
						{
							"id": 1,
							"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml",
							"version": "0.1",
							"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml"
						},
						{
							"id": 2,
							"rawURL": "https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml",
							"version": "0.2",
							"webURL": "https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml"
						}
					]
				},
				"required": ["latest", "versions"]
			}
		},
		"securitySchemes": {
			"jwt_header_Authorization": {
				"type": "http",
				"description": "Secures endpoint by requiring a valid JWT retrieved via the /auth/login endpoint.",
				"scheme": "bearer"
			}
		}
	}
}
